structures:
  cross:
    enable: true
    enable_tnt: true
    tnt_chance: 50
  dungeon:
    enable: true
    depth: -40
  door:
    enable: true
    explosion: true
    explosion_power: 4.0
effects:
  dynamic_lightning:
    enable: true
  night_effects:
    enable: true
    darkness: true
    blindness: true
  cave_effects:
    enable: true
    darkness: true
    blindness: true
    depth: 40