name: Stalker
version: '1.0-SNAPSHOT'
main: greefox.stalker.Stalker
api-version: '1.21'
commands:
  place:
    description: Places a custom structures
    usage: /place <structure>
  stalker:
    description: Kills, spawns or shows a Stalker.
    usage: /stalker <action>
